package constants.enums;

public enum PageNames {
    HOME_PAGE,
    SIGN_IN_PAGE,
    REGISTER_PAGE,
    NOT_FOUND_404,
    TEST_JSP,
    ABOUT_PAGE,
    SHOP,
    Account,
    EditProfile,
    Profile,
    CONTACT_US,
    PRODUCT,
    TRACK_ORDER,
    ADDRESS_BOOK,
    Edit_ADDRESS,
    ADD_ADDRESS,
    EMPTY_SHOP,
    CART,
    EMPTY_CART,
    CHECKOUT,
    MINI_CART,
    CARD_EDIT,
    CARD_DEFAULT,
    CARD_BOOK,
    CARD_ADD,
    TEST_USER_JSP,
    ADD_PRODUCT,
    Error,
    MY_ORDERS,
    CANCELLATIONS,
    USER_DASH_PAGE,
    WISHLIST,
    EMPTY_WISHLIST,
}
